---
ensure_directories:
  - $HOME/wd

ubuntu_tui_apt_packages:
  - git
  - bash-completion
  - curl
  - htop
  - xsel
  - xclip
  - vim-gtk
  - tmux
  - todotxt-cli
  - nodejs

ubuntu_wsl_apt_packages:
  - tmux
  - vim-gtk
  - todotxt-cli

ubuntu_gnome_desktop_apt_packages:
  - gnome-tweak-tool
  - meld
  - clipit

homebrew_installed_packages:
  - bash-completion
  - git
  - reattach-to-user-namespace
  - tmux
  - todo-txt
  - shfmt
  - go
  - dep
  - awscli
  - kubernetes-cli
  # - kubernetes-helm # older version is in use
  - https://raw.githubusercontent.com/Homebrew/homebrew-core/78d64252f30a12b6f4b3ce29686ab5e262eea812/Formula/kubernetes-helm.rb
  - gnupg
  - pinentry-mac

homebrew_taps:
  - homebrew/core
  - homebrew/cask


homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - macvim
  - slack
  - docker
  - visual-studio-code

dotfiles_repo_url: https://github.com/bboykov/dotfiles.git
dotfiles_repo_branch: master
dotfiles_repo_dest: $HOME/dotfiles

ubuntu_wsl_drive_src_dir: /mnt/c/Users/bboykov/drive
ubuntu_wsl_drive_dest_dir: $HOME/drive
