---
ensure_directories:
  - $HOME/wd

ubuntu_tui_apt_packages:
  - git
  - bash-completion
  - curl
  - htop
  - xsel
  - vim-gtk
  - tmux

ubuntu_gnome_desktop_apt_packages:
  - gnome-tweak-tool
  - meld

ubuntu_bare_metal_apt_packages:
  - ubuntu-restricted-extras
  - libdvdnav4
  - libdvdread4
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-plugins-ugly
  - libdvd-pkg

homebrew_installed_packages:
  - bash-completion
  - git
  - reattach-to-user-namespace
  - tmux

homebrew_taps:
  - homebrew/core
  - homebrew/cask


homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - macvim
  - slack

dotfiles_repo_url: https://github.com/bboykov/dotfiles.git
dotfiles_repo_branch: master
dotfiles_repo_dest: $HOME/dotfiles
