---
- name: Clone base16-shell repo
  git:
    repo: https://github.com/chriskempson/base16-shell.git
    dest: ~/.config/base16-shell
    version: master
    depth: 1
  register: is_base16_repo_cloned

- name: Set base16_monokai theme
  command: bash -i -c "base16_monokai"
  when: is_base16_repo_cloned.changed
