---
- name: Install desktop applications
  hosts: localhost
  tasks:
    - name: Update the APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # 1h
      become: true

    - name: Install apps
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - meld

    - name: Install Google Chrome
      import_role:
        name: google-chrome

