---
- name: Configure Windows Subsystem for Linux (Ubuntu)
  hosts: localhost

  vars_files:
    - ../config-vars.yml

  tasks:
    # This task asumes that the src direcory is manually configured with cloud
    # storage service.
    - name: Create symlink to the notes directory
      file:
        src: "{{ ubuntu_wsl_drive_src_dir }}"
        dest: "{{ ubuntu_wsl_drive_dest_dir }}"
        state: link

    - name: Ensure directories exists
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ ensure_directories }}"

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600  # 1h
      become: true

    - name: Install Ubuntu apt packages
      apt:
        state: present
        name: "{{ ubuntu_wsl_apt_packages }}"
      become: true

    - name: Run dotfiles tasks
      include_tasks: ../tasks/dotfiles.yml
      tags:
        - dotfiles

    - name: Run liquidprompt tasks
      include_tasks: ../tasks/liquidprompt.yml
      tags:
        - ps1

    - name: Run VIM tasks
      include_tasks: ../tasks/vim.yml
      tags:
        - vim

    - name: Run base16 shell tasks
      include_tasks: ../tasks/base16.yml
      tags:
        - base16

    - name: Run TMUX tasks
      include_tasks: ../tasks/tmux.yml
      tags:
        - tmux
