---
- name: Configure Windows Subsystem for Linux (Ubuntu)
  hosts: localhost
  tasks:
    # This task asumes that the src direcory is manually configured a cloud
    # storage service.
    - name: Create symlink to the notes directory
      file:
        src: /mnt/c/Users/bboykov/notes
        dest: $HOME/notes
        state: link

    - name: Set the wsl.conf
      copy:
        content: |
          [automount]
          enabled = true
          options = "metadata,umask=22,fmask=11"
        dest: /etc/wsl.conf
      become: true
