---
- name: Configure bare-metal Ubuntu laptop
  hosts: localhost

  vars_files:
    - ../config-vars.yml

  tasks:
    - name: Update the APT cache
      apt:
        update_cache: true
        cache_valid_time: 3600  # 1h
      become: true

      # https://www.tecmint.com/tlp-increase-and-optimize-linux-battery-life/
    - name: Add ppa:linrunner/tlp to install latest tlp
      apt_repository:
        repo: 'ppa:linrunner/tlp'
        state: present
      become: true

    - name: Install battery enchancements
      apt:
        state: present
        name:
          - tlp
          - tlp-rdw
      become: true

    - name: Install apt packages needed on bare-metal
      apt:
        state: present
        name: "{{ ubuntu_bare_metal_apt_packages }}"
      become: true

- name: Configure Vagrant
  hosts: localhost
  tasks:
    # Note that on new laptops there are few things to consiter:
    # 1. Disable UEFI Secure boot or sign the virtualbox modules.
    # See this link for further reading:
    # https://stegard.net/2016/10/virtualbox-secure-boot-ubuntu-fail/
    # 2. Ensure virtualization is enabled from BIOS/UEFI
    - name: Install Virtualbox
      import_role:
        name: virtualbox
      vars:
        virtualbox_version: 6.0
        virtualbox_group_members:
          - root
          - "{{ lookup('env','USER') }}"
      become: true

    - name: Install Vagrant
      import_role:
        name: vagrant
      vars:
        vagrant_version: 2.2.4
        vagrant_dest_path: "/tmp/vagrant_{{ vagrant_version }}"

# - name: Include GNOME Desktop playbook
#   import_playbook: ubuntu-gnome-desktop.yml
