---
- name: Configure GNOME desktop settings
  hosts: localhost

  vars_files:
    - ../vars.yml

  tasks:
    - name: Update the APT cache
      apt:
        update_cache: true
        cache_valid_time: 3600  # 1h
      become: true

    - name: Install Ubuntu GNOME apt packages
      apt:
        state: present
        name: "{{ ubuntu_gnome_desktop_apt_packages }}"
      become: true

    # This depends on the screen(s). Better to be manual setup
    # # High resolutions make text smaller.
    # # https://askubuntu.com/questions/60044/how-do-i-change-the-font-dpi-settings
    # - name: Set text scaling factor
    #   gsettings:
    #     schema: org.gnome.desktop.interface
    #     key: text-scaling-factor
    #     value: 1.1

    - name: Set clock-show-date
      gsettings:
        schema: org.gnome.desktop.interface
        key: clock-show-date
        value: "true"

    - name: Set list-view in the file browser
      gsettings:
        schema: org.gnome.nautilus.preferences
        key: default-folder-viewer
        value: "list-view"

    - name: Set input sources per window
      gsettings:
        schema: org.gnome.desktop.input-sources
        key: per-window
        value: "true"

    - name: Set Dock position on screen
      gsettings:
        schema: org.gnome.shell.extensions.dash-to-dock
        key: dock-position
        value: "BOTTOM"

    - name: Set Dock auto-hide
      gsettings:
        schema: org.gnome.shell.extensions.dash-to-dock
        key: dock-fixed
        value: "false"

    - name: Set show battery percentage
      gsettings:
        schema: org.gnome.desktop.interface
        key: show-battery-percentage
        value: "true"

