---
- name: Configure GNOME Desktop settings
  hosts: localhost
  tasks:
    - name: Update the APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # 1h
      become: true

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - gnome-tweak-tool
        - clipit
        - vim-gtk

    - name: Set locale
      copy:
        content: |
          LANG=en_US.UTF-8
          LC_NUMERIC=en_GB.UTF-8
          LC_TIME=en_US.UTF-8
          LC_MONETARY=en_GB.UTF-8
          LC_PAPER=en_GB.UTF-8
          LC_NAME=en_GB.UTF-8
          LC_ADDRESS=en_GB.UTF-8
          LC_TELEPHONE=en_GB.UTF-8
          LC_MEASUREMENT=en_GB.UTF-8
          LC_IDENTIFICATION=en_GB.UTF-8
          LC_ALL=
        dest: /etc/default/locale
      become: true

    - name: Ensure ~/.font exists
      file:
        path: ~/.fonts
        state: directory
        mode: 0755

    - name: Download DejaVuSansMono nerd font
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/DejaVuSansMono.zip
        dest: ~/.fonts
        remote_src: yes
      register: font_installed

    - name: Run fc-cache -fv
      shell: |
        fc-cache -fv
      args:
        executable: /bin/bash
      when: font_installed.changed

    # gsettings
    - name: Set monospace font
      gsettings:
        schema: org.gnome.desktop.interface
        key: monospace-font-name
        value: "DejaVuSansMono Nerd Font Mono 11"

    # High resolutions make text smaller.
    # https://askubuntu.com/questions/60044/how-do-i-change-the-font-dpi-settings
    - name: Set text scaling factor
      gsettings:
        schema: org.gnome.desktop.interface
        key: text-scaling-factor
        value: 1.3

    - name: Set clock-show-date
      gsettings:
        schema: org.gnome.desktop.interface
        key: clock-show-date
        value: "true"

    - name: Set list-view in the file browser
      gsettings:
        schema: org.gnome.nautilus.preferences
        key: default-folder-viewer
        value: "list-view"

    - name: Set input sources per window
      gsettings:
        schema: org.gnome.desktop.input-sources
        key: per-window
        value: "true"

    - name: Set Dock position on screen
      gsettings:
        schema: org.gnome.shell.extensions.dash-to-dock
        key: dock-position
        value: "BOTTOM"

    - name: Set Dock auto-hide
      gsettings:
        schema: org.gnome.shell.extensions.dash-to-dock
        key: dock-fixed
        value: "false"

    - name: Set show battery percentage
      gsettings:
        schema: org.gnome.desktop.interface
        key: show-battery-percentage
        value: "true"

- name: Install desktop applications
  hosts: localhost
  tasks:
    - name: Update the APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # 1h
      become: true

    - name: Install apps
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - meld

    - name: Install Google Chrome
      import_role:
        name: google-chrome

    - name: Install Dropbox
      import_role:
        name: dropbox
      vars:
        dropbox_downloads_path: /tmp/ansible/dropbox
      become: true
