---
- name: Configure the shell environment
  hosts: localhost
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # 1h
      become: True

    - name: Install packages with APT
      apt:
        name: "{{ item }}"
        state: present
      become: True
      with_items:
        - bash-completion
        - curl
        - git
        - xclip
        - xsel
        - tmux
        - todotxt-cli
        - vim

    - name: Install packages with PIP
      pip:
        name: "{{ item }}"
        state: present
        extra_args: --user
      with_items:
        - awscli

    # dotfiles
    - name: Check if dotfiles repo has been cloned
      stat:
        path: $HOME/dotfiles/
      register: is_dotfiles_cloned
      changed_when: False

    - name: Clone dotfiles repo
      git:
        repo: https://github.com/bboykov/dotfiles.git
        dest: $HOME/dotfiles
        version: master
      register: clone_dotfiles_repo
      when: is_dotfiles_cloned.stat.exists == False

    - name: Run dotfiles script
      shell: |
        cd ~/dotfiles && ./dotfiles.sh
      args:
        executable: /bin/bash
      when: clone_dotfiles_repo.changed

    # tmux
    - name: Check if tmux TPM repo is present
      stat:
        path: ~/.tmux/plugins/tpm
      register: tmux_tpm_repo_is_present
      changed_when: False

    - name: Clone tmux TPM repo
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        depth: 1
      when: tmux_tpm_repo_is_present.stat.exists == False

    # vim
    - name: Check if vim-plug has been installed
      stat:
        path: $HOME/.vim/autoload/plug.vim
      register: is_vim_plug_installed
      changed_when: False

    - name: Install vim-plug
      shell: |
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      args:
        executable: /bin/bash
      when: is_vim_plug_installed.stat.exists == False

    - name: Install plugins with vim-plug - vim +PlugInstall +qall
      command: |
        vim +PlugInstall +qall
      when: is_vim_plug_installed.stat.exists == False

    - name: Update plugins with vim-plug - vim +PlugUpdate +qall
      command: |
        vim +PlugUpdate +qall

    # misc
    - name: Clone base16-shell repo # Set the color theme by running `base16_monokai` in the shell
      git:
        repo: https://github.com/chriskempson/base16-shell.git
        dest: ~/.config/base16-shell
        version: master
        depth: 1

    - name: Clone liquidprompt repo
      git:
        repo: https://github.com/nojhan/liquidprompt.git
        dest: ~/liquidprompt
        version: master
        depth: 1

    # Terraform
    - name: Clone tfenv repo
      git:
        repo: https://github.com/kamatama41/tfenv.git
        dest: ~/.tfenv
        version: master
        depth: 1

    - name: Create symlinks from ~/.tfenv/bin/
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items:
        - { src: ~/.tfenv/bin/terraform , dest: ~/bin/terraform }
        - { src: ~/.tfenv/bin/tfenv , dest: ~/bin/tfenv }
