---
- name: Configure system settings
  hosts: localhost

  vars_files:
    - ../config-vars.yml

  tasks:
    - name: Install Powerline fonts
      import_role:
        name: powerline-fonts
      vars:
        all_fonts:
          - DejaVuSansMono
      tags:
        - fonts

- name: Configure GNOME desktop settings
  hosts: localhost

  vars_files:
    - ../config-vars.yml

  tasks:
    - name: Update the APT cache
      apt:
        update_cache: true
        cache_valid_time: 3600  # 1h
      become: true

    - name: Install Ubuntu GNOME apt packages
      apt:
        state: present
        name: "{{ ubuntu_gnome_desktop_apt_packages }}"
      become: true
