---
- name: Configure Windows Subsystem for Linux (Ubuntu)
  hosts: localhost

  vars_files:
    - ../config-vars.yml

  tasks:
    # This task asumes that the src direcory is manually configured with cloud
    # storage service.
    - name: Create symlink to the notes directory
      file:
        src: "{{ ubuntu_wsl_drive_src_dir }}"
        dest: "{{ ubuntu_wsl_drive_dest_dir }}"
        state: link

    - name: Set the wsl.conf
      copy:
        content: |
          [automount]
          enabled = true
          options = "metadata,umask=22,fmask=11"
        dest: /etc/wsl.conf
      become: true
