---
- name: Configure Ubuntu on bare-metal as primary desktop
  hosts: localhost
  tasks:
    - name: Update the APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # 1h
      become: true

      # https://www.tecmint.com/tlp-increase-and-optimize-linux-battery-life/
    - name: Add ppa:linrunner/tlp to install latest tlp
      apt_repository:
        repo: 'ppa:jonathonf/vim'
        state: present
      become: true

    - name: Install battery enchancements
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - tlp
        - tlp-rdw

    - name: Install graphic packages
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - ubuntu-restricted-extras
        - libdvdnav4
        - libdvdread4
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-plugins-ugly
        - libdvd-pkg

- name: Configure Vagrant environment
  hosts: localhost
  tasks:
    # Note that on new laptops there are few things to consiter:
    # 1. Disable UEFI Secure boot or sign the virtualbox modules.
    # See this link for further reading - https://stegard.net/2016/10/virtualbox-secure-boot-ubuntu-fail/
    # 2. Ensure virtualization is enabled from BIOS/UEFI
    - name: Install Virtualbox
      import_role:
        name: virtualbox
      vars:
        virtualbox_version: 5.2
        virtualbox_group_members:
          - root
          - "{{ lookup('env','USER') }}"
      become: true

    - name: Install Vagrant
      import_role:
        name: vagrant
      vars:
        vagrant_version: 2.0.1
        vagrant_dest_path: "/tmp/ansible/vagrant_{{ vagrant_version }}"

- name: Configure development applications
  hosts: localhost
  tasks:
    - name: Install Docker
      import_role:
        name: docker
      vars:
        docker_users:
          - bboykov
      become: true
